### ISSUE TITLE
TKabber users gets links in conference from Kaiwa as PM

### ISSUE THREAD

**Issue by unclechu** [ForNeVeR/kaiwa#116] opened 2016-03-10 13:56 UTC
Some guy with TKabber client gets links that send to conference from Kaiwa as personal messages, this guy sent us screenshot: http://cloud.ubunix.ru/index.php/s/d7CYOqtrmBq29LG

**Comment by vitalyster** [comment] 2016-03-10 13:58
duplicate of #106

**Closed by vitalyster** 2016-03-10 13:58 UTC
