### ISSUE TITLE
header.css file

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#25] opened 2015-09-08 15:08 UTC
I cannot get whether this file was compiled with stylus or not; it is also unknown whether it is used by current code or not. We should investigate.

**Comment by vitalyster** [comment] 2015-09-08 15:18
Duplicate of #19

**Comment by ForNeVeR** [comment] 2015-09-08 15:19
No it is not. #19 is all about `client.css`; this is about `header.css`.

**Comment by vitalyster** [comment] 2015-09-08 15:24
there is a `header.styl` which included from `client.styl` and stylus successfully compiles `client.css` and it matches repo version

**Closed** 2015-09-09 17:00 UTC
Labels: infrastructure, minor
